### ISSUE TITLE
GeoJSON ID length default

### ISSUE THREAD

**Issue by invisiblefunnel** [sharedstreets/sharedstreets-python#13]
@migurski id trimming for GeoJSON defaults to 12 (of 32 total) characters. How do you feel about defaulting to the full-length id, and letting the caller specify a lower number? Not trimming by default seems like a less surprising behavior.

https://github.com/sharedstreets/sharedstreets-python/blob/75205e2e0fb178e4b0cd457d2a665e1d1fa46ca5/sharedstreets/tile.py#L212

**Comment by migurski** [comment]
I’m good with it.

**Comment by kpwebb** [comment]
Just made this change (see PR #15 ). Now that we're providing a global API end-point that uses these IDs, we should stick with using the globally unique full 32 char version.

**Comment by migurski** [comment]
Sounds great. We’re using 12-char IDs internally with the `id_length` parameter, but this default change shouldn't affect our usage.

**Comment by kpwebb** [comment]
@migurski good to know! We'll add a startsWith lookup to the API so we can resolve partial IDs. Likely there will be ID collisions globally when truncated to 12 char id, but they should still be unique *mostly* within your local deployments.  I'm guessing a a tile id + a 12 char id should be unique. But now that we've built a global index of all the IDs, I can check and make sure that's true!

**Comment by migurski** [comment]
I’m curious to see what you find! We’ve been thinking that short IDs are enough for local areas and that we’d generally be searching in small zones.
