### ISSUE TITLE
python example results in empty geojson file

### ISSUE THREAD

**Issue by kpwebb** [sharedstreets/sharedstreets-python#14]
@migurski just discovered that the GeoJSON CLI example in the docs returns a zero size feature collection:

sharedstreets-get-tile 16 10509 25324 > 16-10509-25324.geojson

I'm debugging, but also curious if there are any changes on your end that are pushed. We're bringing on a new person on end (hi @vipassana!) who will be working with the Python lib. Just want to make sure we have the latest and greatest!

**Comment by migurski** [comment]
That’s odd! I am running the same command using the current version from this repository and seeing meaningful output for tile [16/10509/25324](https://tile.openstreetmap.org/16/10509/25324.png):

<img width="821" alt="screen shot 2018-07-17 at 1 30 17 pm" src="https://user-images.githubusercontent.com/58730/42843641-9b24415c-89c5-11e8-884f-a47bed5e5f2c.png">

**Comment by kpwebb** [comment]
we were getting intermittent results too! 

When we installed fresh we get a blank result. But I got a result when i ran from my laptop, even if we blew away the repo. I'm curious if there's something in the environment on our laptops that's changed if you start fresh...

**Comment by migurski** [comment]
I don’t have an explanation for the behavior you’re seeing. There isn’t any environment variable that affects normal operation, and I can’t think of a reason why it’d work intermittently. The protobuf URL being downloaded is defined [on line 9 of `tile.py`](https://github.com/sharedstreets/sharedstreets-python/blob/master/sharedstreets/tile.py#L9).

**Comment by kpwebb** [comment]
@migurski tracked this down turns out that the URL requests were failing because the `data_zxy` object contained floats and was getting converted to a string with trailing zero decimals included. 

No idea what changed, but seems like it was environmentally dependent. Maybe an upstream library changed behavior?

Anyhow, pushed a fix as pull #15

**Comment by migurski** [comment]
Thanks for tracking that down — I’m curious what version of Python you were using, because I can’t think of a reason this behavior would show up for you but not in tests or for me. Thanks for the PR!

**Comment by kpwebb** [comment]
We were running it on 2.7.x but only showed up when freshly installed. When I ran it from source (even from a clean github clone) it worked on my laptop. But deployments on machines where SharedStreets hadn't been installed previously failed. No idea why...

**Comment by migurski** [comment]
Weird. I wish our test coverage surfaced this behavior.
