### ISSUE TITLE
Simplify purpose of sharedstreets-python

### ISSUE THREAD

**Issue by DenisCarriere** [sharedstreets/sharedstreets-python#5]
## Simplify purpose of `sharedstreets-python`

Right now, the Python library not heading in a focused direction. We've already got a lot of tools built on the Javascript (NodeJS) side which allows server & browser compatibility.

The original purpose of the Python library was for simple to use SharedStreet methods:

- Hash a Message
- Convert a Geometry to ID
- Convert an Intersection to ID
- etc...

All other tooling should be done in NodeJS that way we have the code ready for the browser when we need it.

From my point of view, only the following core SharedStreets tools should exist in NodeJS:

- [x] Convert PBF to JSON - [`sharedstreets-pbf`](https://github.com/sharedstreets/sharedstreets-pbf) (already completed)
- [ ] Convert JSON to GeoJSON - `sharedstreets-geojson` (port from python)
- [ ] Download tile from SharedStreets tile server - `sharedstreets-tile` (port from python)

**Comment by migurski** [comment]
For my own use, having tools in NodeJS is not actually helpful unless they're truly standalone. Converting PBF to other formats may need to happen in a library context, integrated into another codebase.

**Comment by kpwebb** [comment]
Just +1 for @migurski point -- I think we need multi-language support, as we want folks to integrate SharedStreets data standards into their internal platforms/data workflows so we can't take a position on language/architecture. 

We'll probably rely more on the JS versions (for the time being) for our SharedStreets data workflow/QA process, but doesn't diminish the need for other languages to have parity with client libs.

Just add a near-term justification: full Python support will be crucial for ESRI and QGIS plugins.

**Comment by kpwebb** [comment]
Going back to #1 let's make a list of key functionality we want to see in client-libs (using the current JS and Python libs as references). Ok with me if these aren't at 100% parity for the moment, but useful as a goal. And we can point to that for future libs in other languages (can see formal Java support useful)

**Comment by migurski** [comment]
Key functionality I’d expect to see in a client library, with checks for the ones that exist here in Python:

- [x] Protobuf code to access upstream SharedStreets data
- [ ] Conversion functions for PBF data into something locally useful:
  - [x] GeoJSON
  - [ ] GIS features, such as OGR or ESRI depending on environment
- [x] ID calculation for local data
- [ ] Dataset conflation with other local data

Additional stuff that could be interesting depending on client language conventions:

- [x] Ability to serve GeoJSON tiles
- [ ] Conversion to NetworkX with OSMnx compatibility, for Python
- [ ] Detail reduction by road class clipping
- [ ] Ability to map properties or features onto SharedStreets geometries

**Comment by migurski** [comment]
This issue feels safe to close; hope that’s okay with folks.
